name: Adding test coverage to CodeCov

on: [push,pull_request]

env:
  APP_WORKING_DIR: app
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependences
        run: npm install

      - name: Running test with coverage
        run: npm run test:cov
      
      - name: Upload unit test result
        uses: actions/upload-artifact@v3
        with:
          name: node-unit-coverage
          path: ${{ env.APP_WORKING_DIR }}/coverage
      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     files: ./coverage/cobertura-coverage.xml
      #     name: node-coverage
        # env:
        #   CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  upload-coverage:
    runs-on: ubuntu-latest
    needs: run-test
    steps:
      - name: Download unit test coverage
        uses: actions/download-artifact@v3
        with:
          name: node-unit-coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/cobertura-coverage.xml
          name: node-coverage
